const CONTACTS_STATICS_EN = {
  LABELS: {
    CONTACT: 'CONTACT',
    INVITATIONS: 'INVITATIONS',
    SETTINGS: 'SETTINGS',
    BIRTHDAY: 'BIRTHDAY',
    NOTIFICATIONS: 'NOTIFICATIONS',
    INFO: 'INFO',
    MACH_DIR: 'Mach Dir Notizen uber diese Person...',
    SEARCH_CHAT: 'SEARCH CHAT',
    CLEAR_CHAT: 'CLEAR CHAT',
    SAVE: 'SAVE',
    Delete: 'Contact Delete',
    BLOCK_CONTACT: 'BLOCK CONTACT',
    UNBLOCK_CONTACT: 'UNBLOCK CONTACT',
    INVITE_SENT: 'INVITE SENT',
    BLOCKED_BY_OTHER: 'BLOCKED BY OTHER',
    TYPE_A_MESSAGE: 'Type a message',
    No_name: 'No name',
    You_can_add_max: 'You can add max',
    participants: 'participants.',
    Already_added: 'Already added',
    clear_chat: 'Are you want to clear chat?',
    NO: 'NO',
    YES: 'YES',
    Contact_deleted_successfully: 'Contact deleted successfully!',
    to_delete_this_contact: 'Do you want to delete this contact?',
    all_chat_cleared_now: 'All chats have been cleaned now!',
    chat_cleared_now: 'Chat has been cleaned now!',
    ADD_PARTICIPANT: 'Add Participant',
    SEARCH: 'Search',
    NEXT: 'Next',
    CREATE: 'Create',
    BLOCKED: 'Do you want to block otherPersonContactName contact?',
    CANCEL: 'Cancel',
    CHOOSE: 'Choose',
    YOU_ARE_BLOCKED: 'You are blocked!',
    GROUP_NAME_REQ: 'Group Name is required',
  },
  BUTTONS: {
    READ_MORE: 'Read more',
    NEW_GROUP: 'New Group',
  },
};

export default CONTACTS_STATICS_EN;
