const CONTACTS_STATICS_EN = {
  LABELS: {
    CONTACT: 'KONTAKTE',
    INVITATIONS: 'EINLADUNGEN',
    SETTINGS: 'EINSTELLUNGEN',
    BIRTHDAY: 'GEBURTSTAGE',
    NOTIFICATIONS: 'NACHRICHTEN',
    INFO: 'INFO',
    MACH_DIR: 'Mach dir eine Notiz über diese Person...',
    SEARCH_CHAT: 'CHAT DURCHSUCHEN',
    CLEAR_CHAT: 'CHAT LÖSCHEN',
    SAVE: 'SPEICHERN',
    Delete: 'Kontakte Löschen',
    BLOCK_CONTACT: 'NUTZER*IN BLOCKIEREN',
    UNBLOCK_CONTACT: 'USER ENTSPERREN',
    INVITE_SENT: 'EINLADUNG GESENDET',
    BLOCKED_BY_OTHER: 'BLOCKED BY OTHER',
    TYPE_A_MESSAGE: 'Eine Nachricht eingeben',
    No_name: 'Kein Name',
    You_can_add_max: 'Du kannst maximal',
    participants: 'Teilnehmer*inner',
    Already_added: 'Bereits hinzugefügt',
    clear_chat: 'Möchtest du den Chat löschen?',
    NO: 'NEIN',
    YES: 'JA',
    Contact_deleted_successfully: 'Kontakt wurde erfolgreich gelöscht!',
    to_delete_this_contact: 'Möchtest du diesen Kontakt löschen?',
    all_chat_cleared_now: 'Alle Chatinhalte wurden gelöscht!',
    chat_cleared_now: 'Alle Chatinhalte wurden gelöscht!',
    ADD_PARTICIPANT: 'Teilnehmer*innen hinzufügen',
    SEARCH: 'Suche',
    NEXT: 'Weiter',
    CREATE: 'Erstellen',
    BLOCKED: 'Möchtest du otherPersonContactName blockieren?',
    CANCEL: 'Abbrechen',
    CHOOSE: 'Auswählen',
    YOU_ARE_BLOCKED: 'Du wurdest blockiert',
    GROUP_NAME_REQ: 'Die Gruppe braucht einen Namen',
  },
  BUTTONS: {
    READ_MORE: 'Mehr lesen',
    NEW_GROUP: 'Neue Gruppe',
  },
};

export default CONTACTS_STATICS_EN;
